### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by Alex61NN5** [Alex61NN5/easy-read-time#2]

**Comment by arturparkhisenko** [comment]
@Alex61NN5 can I take this one? Hacktoberfest :)

**Comment by Alex61NN5** [comment]
@arturparkhisenko all yours!!

**Comment by arturparkhisenko** [comment]
@Alex61NN5 would you like to see them using [jest](https://github.com/facebook/jest)? Or if you have any other test framework preference.
